version: '3.8'
services:
  develop-db:
    container_name: 'schedulize-devdb'
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - .dev/db:/var/lib/postgresql/data
